# This workflow will build a Java project with Gradle
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Build project and upload JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: valheim-save-tools.jar
        path: ./build/libs/valheim-save-tools.jar
    - name: Publish SNAPSHOT Maven package
      if: github.ref == 'refs/heads/master'
      run: ./gradlew publish -PonlyPublishSnapshotVersion
      env:
        GITHUB_PACKAGES_WRITE_TOKEN: ${{ secrets.PACKAGES_WRITE_TOKEN }}
